---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "pre-commit"




# dependabot-trigger: 2026-08-10T20:37:30Z
