---
name: Anchore Syft SBOM scan

"on":
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  Anchore-SBOM:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Scan the repository and upload dependency results
        uses: anchore/sbom-action@aa80c8c5bd439a416a62804f2151ab38c671a638
        with:
          path: .
          artifact-name: sbom.spdx.json
          dependency-snapshot: true
