---
name: Anchore Syft SBOM scan

"on":
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  Anchore-SBOM:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Scan the repository and upload dependency results
        uses: anchore/sbom-action@66cbf4bc1f1c0d2edc94016e65bc221b6bb0ad6c
        with:
          path: .
          artifact-name: sbom.spdx.json
          dependency-snapshot: true
